version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:15.15-trixie
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: drf-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/geekchanskiy/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"